type: script
name: apache_range
version: "2.0"
dependencies:
  library:
    - core
  system:
    - libwww-perl
inputs:
  - name: range
    type: text
    description: Number of ranges to test
    value: 10
