type: script
name: subdomain_dict
version: 2.0
dependencies:
  system:
    - libnet-dns-perl
  library:
    - core
inputs:
  - name: big_file
    type: checkbox
    description: Use big file (5600+ entries)
