type: script
name: ig_email_yahoo_api
version: 2.2
dependencies:
  library:
    - core
    - yahoo_api
    - emailgrabber
inputs:
  - name: api_key
    type: text
    description: Yahoo API key
    visible: false
  - name: client_secret
    type: text
    description: Client secret key
    visible: false
