type: script
name: shell
version: 2.0
dependencies:
  library:
    - core
inputs:
  - name: command
    type: text
    description: "Command to run. Use @target to insert a target into command (ex: ping -c 3 @target)."
