type: script
name: ig_subdomain_bruteforce
version: 2.0
dependencies:
  library:
    - core
  system:
    - python-dnspython
inputs:
  - name: min_length
    type: text
    description: Minimum subdomain length
    value: 1
  - name: max_length
    type: text
    description: Maximum subdomain length
    value: 3
