type: script
name: ftp_bruteforce
version: "2.0"
dependencies:
  library:
    - core
inputs:
  - name: users
    type: textarea
    description: User list
  - name: passwords
    type: textarea
    description: Password list
