type: script
name: urlscan
version: 1.7
dependencies:
  system:
    - libwww-perl
  library:
    - core
inputs:
  - name: urls
    type: textarea
    description: URLs to scan
    value: "admin\nadmin.php\nadmin.cfm"
