type: script
name: urlscan
version: 2.0
dependencies:
  system:
    - libwww-perl
  library:
    - core
inputs:
  - name: urls
    type: textarea
    description: URLs to scan
    value: "admin\nadmin.php\nadmin.cfm"
