type: script
name: dns_b_nr
version: 1.7
dependencies:
  library:
    - core
  system:
    - python-dnspython
inputs:
  - name: host
    type: text
    description: Hostname for DNS query
    value: microsoft.com
