type: script
name: nic_typosquatting
version: 2.0
dependencies:
  library:
    - core
  system:
    - libnet-dns-perl
inputs:
  - name: timeout
    type: text
    description: TCP timeout
    value: 120
  - name: max_results
    type: text
    description: Maximum number of results
    value: 100
  - name: detect_ip
    type: checkbox
    description: Detect IPs
    value: 1
