type: script
name: metasploit
version: 1.7
dependencies:
  library:
    - core
  system:
    - metasploit_4.11.9_amd64.deb
inputs:
  - name: script
    type: textarea
    description: Metasploit script
