type: script
name: metasploit
version: "2.0"
dependencies:
  library:
    - core
  deb:
    - metasploit-framework_4.11.9_amd64.deb
inputs:
  - name: script
    type: textarea
    description: Metasploit script
