type: script
name: ig_domain_rr
version: "2.0"
dependencies:
  library:
    - core
  system:
    - libc-ares2
  deb:
    - reverseraider_0.7.7-1_amd64.deb
inputs:
  - name: word_list
    type: radio
    description: "Word list to use."
    value: "fast\nservices\nfull"
