type: script
name: dns_a_nr
version: "2.0"
dependencies:
  library:
    - core
  system:
    - python-dnspython
inputs:
  - name: host
    type: text
    description: Hostname for DNS query
    value: microsoft.com
