type: script
name: apache_dos
version: 1.7
dependencies:
  library:
    - core
  system:
    - libwww-perl
inputs:
  - name: range
    type: text
    description: Number of ranges to test
    value: 10
