type: script
name: smtp_relay
version: "2.0"
dependencies:
  library:
    - core
inputs:
  - name: timeout
    type: text
    description: TCP timeout
    value: 120
  - name: email_from
    type: text
    description: Source email
  - name: email_to
    type: text
    description: Destination email
