type: script
name: www_auth_scanner
version: 1.7
dependencies:
  system:
    - libwww-perl
    - libcrypt-ssleay-perl
  library:
    - core
inputs:
  - name: urls
    type: textarea
    description: URLs to scan
    value: "auth\nadmin\nlogin"
