type: script
name: login_pages
version: 1.7
dependencies:
  library:
    - core
  system:
    - libwww-perl
inputs:
  - name: code
    type: text
    description: Type of code on web-server (asp, cfm, php)
    value: php
