type: script
name: w3af_finger_google
version: "2.0"
dependencies:
  library:
    - core
    - w3af
inputs:
  - name: result_limit
    type: text
    description: Result limit number
    value: 300
  - name: fast_search
    type: checkbox
    description: Use fast search
    value: 1
