type: script
name: www_file_scanner
version: 2.0
dependencies:
  system:
    - libwww-perl
    - libcrypt-ssleay-perl
  library:
    - core
inputs:
  - name: urls
    type: textarea
    description: URLs to scan
    value: "robots.txt\nlogin.php\nphpinfo.php"
