type: script
name: webserver_files
version: "2.0"
dependencies:
  system:
    - libwww-perl
  library:
    - core
inputs:
- name: Admin_Logins
  type: file
- name: Adobe_xml
  type: file
- name: Apache_Dojo_Framework
  type: file
- name: Apache_Tomcat_Application_Server
  type: file
- name: Apache_Web_Server
  type: file
- name: Backend_Dirs
  type: file
- name: CA_Siteminder_Adminstration
  type: file
- name: Checkpoint_Firewall_Web_Interface
  type: file
- name: Citrix_Application_Server
  type: file
- name: Cold_Fusion_Application_Server
  type: file
- name: ContentXXL_Cms
  type: file
- name: DotProject
  type: file
- name: Drupal_Cms
  type: file
- name: Fatwire_CMS
  type: file
- name: Hyperion_CMS
  type: file
- name: Ibm_Websphere_Application_Server
  type: file
- name: Iis_Web_Server
  type: file
- name: J2EE_JRUN_Application_Server
  type: file
- name: Java_servlets_and_jboss
  type: file
- name: Jira_JSP
  type: file
- name: Joomla_Cms_Dirs
  type: file
- name: Lotus_Domino_Web_Server
  type: file
- name: Mbrs_Php
  type: file
- name: Nikto_Database_Checks
  type: file
- name: Novell_Access_Manager_and_Netware
  type: file
- name: Oracle_Web_and_Application_Server
  type: file
- name: Php_requests
  type: file
- name: Phpmyadmin_Cms
  type: file
- name: Piwik_Webalyzer
  type: file
- name: Proxy_Test
  type: file
- name: SAP_Web_Server
  type: file
- name: Sharepoint_Application_Server
  type: file
- name: Symfony_Cms
  type: file
- name: Typo3_Cms
  type: file
- name: Unix_Files
  type: file
- name: Vignette_Cms
  type: file
- name: Vuln_Files
  type: file
- name: Winlike
  type: file
- name: Wordpress_Cms
  type: file
- name: checkpoint_sslnetwork_extender
  type: file
