type: script
name: ig_domain_bing_api
version: 2.0
dependencies:
  library:
    - core
    - bing_api
    - emailgrabber
inputs:
  - name: api_key
    type: text
    description: Bing API key
    visible: false
