type: script
name: smtp_filter
version: "2.0"
dependencies:
  library:
    - core
inputs:
  - name: tls
    type: checkbox
    description: Enable TLS support.
    value: 1
  - name: recipient
    type: text
    description: Recipient email
  - name: smtp_login
    type: text
    description: SMTP login
  - name: smtp_password
    type: text
    description: SMTP password
  - name: sender
    type: text
    description: Sender email
  - name: folder
    type: radio
    description: "Folder to use for test"
    value: "Encrypted\nLevel1\nLevel2\nLevel3\nMacroGeneralTest\nMacroInsideOut\nMixedLevels\nPDFExploits\nPDFJS\nProfanity\nTestVirusandTrojans\nOfficeExploits"
