type: script
name: www_dir_scanner
version: "2.0"
dependencies:
  system:
    - libwww-perl
    - libcrypt-ssleay-perl
  library:
    - core
inputs:
  - name: urls
    type: textarea
    description: URLs to scan
    value: "auth\nadmin\nlogin\nmail"
