type: script
name: ig_domain_spyonweb
version: 2.2
dependencies:
  library:
    - core
  system:
    - python-requests
inputs:
  - name: api_key
    type: text
    description: Spyonweb API key
    visible: false
