type: script
name: ssh_bruteforce
version: 1.7
dependencies:
  system:
    - libnet-ssh2-perl
  library:
    - core
inputs:
  - name: users
    type: textarea
    description: User list
  - name: passwords
    type: textarea
    description: Password list
